name: Mock Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'sandbox'

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start Vite dev server and run Cypress tests
        run: npx start-server-and-test "npm run dev" http://localhost:3000 "npm run cypress"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t your-app:latest .

      - name: Tag Docker image for mock ECR
        run: |
          MOCK_REGISTRY=mock.ecr.registry.local/your-app
          docker tag your-app:latest $MOCK_REGISTRY:latest

      - name: Push Docker image to a mock registry
        run: |
          MOCK_REGISTRY=mock.ecr.registry.local/your-app
          echo "Pushing to simulated registry: $MOCK_REGISTRY"
          echo "Simulating docker push $MOCK_REGISTRY:latest"

      - name: Simulate ECS Deployment
        run: |
          echo "Simulating ECS Deployment with Docker image:"
          echo "Using tag: your-app:latest from mock registry"
          echo "Deployment successful."
